#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running tests

golint $(go list ./... 2> /dev/null | grep -v /vendor/)
go vet $(go list ./... 2> /dev/null | grep -v /vendor/)
go test $(go list ./... 2> /dev/null | grep -v /vendor/)
